/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on May 29, 2021, 10:56:07 AM
 */
package ProjekUAS;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Yuu
 */
public class Anggota extends javax.swing.JFrame {
public static ArrayList<AnggotaData> listData = new ArrayList<AnggotaData>();
public static ArrayList<AnggotaData> getList() {
       return listData;
}
DefaultTableModel tabelModel;


    public Anggota() {
        setSize(900, 600);
        setLocationRelativeTo(null);
        initComponents();
        tampilData();
        
        
    }
    private void tampilData(){
        String[] kolom = {"ID","NAMA","KELAS","KELAMIN","ALAMAT","NO HP","EMAIL"};
        Object[][] objData = new Object[listData.size()][7]; // 7 merupakan jumlah kolom
        
        int i = 0;
        for(AnggotaData n : listData){
            String[] arrData = { (n.getID()), n.getNamaA(),n.getKelas(),n.getGender(), n.getAlamat(), n.getNHP(), n.getEmail()};
            objData[i] = arrData;
            i++;
        }
        
        tabelModel = new DefaultTableModel(objData,kolom){
            //membuat tabel tidak bisa diedit saat diklik
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        TableAng.setModel(tabelModel);
    }
    
    public void isiData(String ID, String NamaA, String Kelas,String Gender, String Alamat,String NHP, String Email){
        AnggotaData ed = new AnggotaData(ID, NamaA, Kelas, Gender, Alamat, NHP, Email);
        listData.add(ed);
    }
    

    private void resetInputan(){
        txtID.setText("");
        txtNama.setText("");
        txtKelas.setText("");
        txtGender.setText("");
        txtAlamat.setText("");
        txtNHP.setText("");
        txtEma.setText("");
        txtCari.setText(null);
        txtID.requestFocus();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtEma = new javax.swing.JTextField();
        txtNHP = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        cmbJK = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAng = new javax.swing.JTable();
        BTambah = new javax.swing.JButton();
        MEdit = new javax.swing.JButton();
        MHapus = new javax.swing.JButton();
        MKembali = new javax.swing.JButton();
        MKeluar = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel8.setText("DAFTAR ANGGOTA PERPUSTAKAAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("ID Anggota ");

        jLabel2.setText("Nama Anggota");

        jLabel3.setText("Kelas");

        jLabel6.setText("Email");

        jLabel7.setText("No HP");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtNHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNHPKeyTyped(evt);
            }
        });

        jLabel5.setText("Alamat");

        txtGender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGenderKeyTyped(evt);
            }
        });

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih jenis kelamin", "Laki-laki", "Perempuan"}));
        cmbJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEma, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNHP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(71, 71, 71))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtEma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        TableAng.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableAng.setColumnSelectionAllowed(true);
        TableAng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAngMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAng);
        TableAng.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BTambah.setText("Tambah");
        BTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTambahActionPerformed(evt);
            }
        });

        MEdit.setText("Edit");
        MEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEditActionPerformed(evt);
            }
        });

        MHapus.setText("Hapus");
        MHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MHapusActionPerformed(evt);
            }
        });

        MKembali.setText("Kembali");
        MKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKembaliActionPerformed(evt);
            }
        });

        MKeluar.setText("Keluar");
        MKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKeluarActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jLabel9.setText("Cari");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(MHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MEdit)
                    .addComponent(BTambah)
                    .addComponent(MKeluar)
                    .addComponent(MKembali)
                    .addComponent(MHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKembaliActionPerformed
        new Utama().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_MKembaliActionPerformed

    private void MKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKeluarActionPerformed
        int pilih = javax.swing.JOptionPane.showOptionDialog(this, 
                        "Yakin ingin keluar?", 
                        "", 
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(pilih == javax.swing.JOptionPane.YES_OPTION){
            javax.swing.JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_MKeluarActionPerformed

    private void BTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTambahActionPerformed
 
        if(txtID.getText().equals("")
                || txtNama.getText().equals("")
                || txtKelas.getText().equals("")
                ||txtGender.getText().equals("")
                ||txtAlamat.getText().equals("")
                ||txtNHP.getText().equals("")
                ||txtEma.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(this, "Data masih kosong!!");
        }
        if (txtID.getText().equals("")) txtID.setText("-wajib diisi-");
        if(txtNama.getText().equals("")) txtNama.setText("-wajib diisi-");
        if(txtKelas.getText().equals("")) txtKelas.setText("-wajib diisi-");
        if(txtGender.getText().equals("")) txtGender.setText("-wajib diisi-");
        if(txtAlamat.getText().equals("")) txtAlamat.setText("-wajib diisi-");
        if(txtNHP.getText().equals("")) txtNHP.setText("-wajib diisi-");
        if(txtEma.getText().equals("")) txtEma.setText("-wajib diisi-");
        if(txtID.getText().equals("-wajib diisi-")
                || txtNama.getText().equals("-wajib diisi-")
                || txtKelas.getText().equals("-wajib diisi-")
                ||txtGender.getText().equals("-wajib diisi-")
                ||txtAlamat.getText().equals("-wajib diisi-")
                ||txtNHP.getText().equals("-wajib diisi-")
                ||txtEma.getText().equals("-wajib diisi-")){
            javax.swing.JOptionPane.showMessageDialog(this, "Harap isi data yang benar!!");
        }        
        else {
            isiData(txtID.getText(),txtNama.getText(), txtKelas.getText(),txtGender.getText(),txtAlamat.getText(), txtNHP.getText(),txtEma.getText());
                    TableAng.setRowSorter(null);
        tampilData();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!!");
        resetInputan();
        }
    }//GEN-LAST:event_BTambahActionPerformed

    private void MHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MHapusActionPerformed
        int i = TableAng.getSelectedRow();
        i = TableAng.convertRowIndexToModel(i);
        if (i==-1) {javax.swing.JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih !!");
        }
        else if(i>=0){
            listData.remove(i);
            javax.swing.JOptionPane.showMessageDialog(null, "Data berhasil dihapus !!");       
        } 
        else {
            javax.swing.JOptionPane.showMessageDialog(null, "Hapus data gagal, Coba lagi!!");
        }
        resetInputan();
        TableAng.setRowSorter(null);
        tampilData();
    }//GEN-LAST:event_MHapusActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        String cari = txtCari.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel);
        TableAng.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari));//fungsi (?i)Agar huruf kapital dan kecil tetap dibaca
        if (TableAng.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "Item yang di cari tidak ada di list");
            TableAng.setRowSorter(null);
            txtCari.setText("");
            resetInputan();
        }                               
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void MEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEditActionPerformed
        int i = TableAng.getSelectedRow();
        int a = TableAng.getSelectedRow();
            a = TableAng.convertRowIndexToModel(i);
      if (i == -1||a<=-1) {javax.swing.JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih !!");
        }
      else if(txtID.getText().equals("")
                || txtNama.getText().equals("")
                || txtKelas.getText().equals("")
                ||txtGender.getText().equals("")
                ||txtAlamat.getText().equals("")
                ||txtNHP.getText().equals("")
                ||txtEma.getText().equals("")){                        
        txtID.setText(TableAng.getValueAt(i, 0).toString());
        txtNama.setText(TableAng.getValueAt(i, 1).toString());
        txtKelas.setText(TableAng.getValueAt(i, 2).toString());
        txtGender.setText(TableAng.getValueAt(i, 3).toString());
        txtAlamat.setText(TableAng.getValueAt(i, 4).toString());
        txtNHP.setText(TableAng.getValueAt(i, 5).toString());
        txtEma.setText(TableAng.getValueAt(i, 6).toString());       
        }
         else if(txtID.getText().equals("")
                || txtNama.getText().equals("")
                || txtKelas.getText().equals("")
                ||txtGender.getText().equals("")
                ||txtAlamat.getText().equals("")
                ||txtNHP.getText().equals("")
                ||txtEma.getText().equals(""))
         {
             txtID.setText("-wajib diisi-");
             txtNama.setText("-wajib diisi-");
             txtKelas.setText("-wajib diisi-");
             txtGender.setText("-wajib diisi-");
             txtAlamat.setText("-wajib diisi-");
             txtNHP.setText("-wajib diisi-");
             txtEma.setText("-wajib diisi-");
         }
         else if(txtID.getText().equals("-wajib diisi-")
                || txtNama.getText().equals("-wajib diisi-")
                || txtKelas.getText().equals("-wajib diisi-")
                ||txtGender.getText().equals("-wajib diisi-")
                ||txtAlamat.getText().equals("-wajib diisi-")
                ||txtNHP.getText().equals("-wajib diisi-")
                ||txtEma.getText().equals("-wajib diisi-")){
            javax.swing.JOptionPane.showMessageDialog(this, "Harap isi data yang benar!!");
        } else if(i>=0){
           isiData(txtID.getText(),txtNama.getText(), txtKelas.getText(),txtGender.getText(),txtAlamat.getText(), txtNHP.getText(),txtEma.getText());
            listData.remove(a);
            TableAng.setRowSorter(null);
            tampilData();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil di edit");
                    resetInputan();          
        }      
         else {
            isiData(txtID.getText(),txtNama.getText(), txtKelas.getText(),txtGender.getText(),txtAlamat.getText(), txtNHP.getText(),txtEma.getText());
            listData.remove(i);
            TableAng.setRowSorter(null);
            tampilData();
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil di edit");
                    resetInputan();
            
             }
 
                  
    }//GEN-LAST:event_MEditActionPerformed

    private void TableAngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAngMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableAngMouseClicked

    private void cmbJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJKActionPerformed
        String jenis,gender = null;
        
        jenis = String.valueOf(cmbJK.getSelectedItem());
        if (jenis.equals("Laki-laki")){
            gender = "Laki-laki";
        }
        if (jenis.equals("Perempuan")){
            gender = "Perempuan";
        } else{
            jenis ="pilih jenis kelamin";
        }
        txtGender.setText(gender);
    }//GEN-LAST:event_cmbJKActionPerformed

    private void txtNHPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNHPKeyTyped
    char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||(ch==KeyEvent.VK_BACK_SPACE)||(ch==KeyEvent.VK_DELETE)))
        {evt.consume();
        
        }
    }//GEN-LAST:event_txtNHPKeyTyped

    private void txtGenderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGenderKeyTyped
    char ch=evt.getKeyChar();       
        evt.consume();
        
    }//GEN-LAST:event_txtGenderKeyTyped
                                       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Anggota().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTambah;
    private javax.swing.JButton MEdit;
    private javax.swing.JButton MHapus;
    private javax.swing.JButton MKeluar;
    private javax.swing.JButton MKembali;
    private static javax.swing.JTable TableAng;
    private javax.swing.JComboBox cmbJK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtEma;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtNHP;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
