/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameUAS.java
 *
 * Created on May 24, 2021, 9:10:16 AM
 */
package ProjekUAS;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Yuu
 */
public class DaftarBuku extends javax.swing.JFrame {
public static ArrayList<DataBuku> listDataB = new ArrayList<DataBuku>();
public static ArrayList<DataBuku> getList() {
       return listDataB;
}
DefaultTableModel tabelModel2;


    public DaftarBuku() {
        setSize(900, 600);
        setLocationRelativeTo(null);
        initComponents();
        tampilDataB();
    }
    private void tampilDataB(){
        String[] kolom = {"KODE","JUDUL","PENERBIT","PENGARANG","TAHUN TERBIT"};
        Object[][] objData = new Object[listDataB.size()][5];//jumlah kolom
        
        int i = 0;
        for(DataBuku n : listDataB){
            String[] arrData = {n.getKBuku(), n.getJBuku(),n.getPenerbit(),n.getPengarang(), String.valueOf(n.getTTerbit())};
            objData[i] = arrData;
            i++;
        }
        
        tabelModel2 = new DefaultTableModel(objData,kolom){
            //membuat tabel tidak bisa diedit saat diklik
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        TableBu.setModel(tabelModel2);
    }
    
    public void isiData(String KBuku, String JBuku, String Penerbit,String Pengarang, int TTerbit){
        DataBuku ed = new DataBuku(KBuku, JBuku, Penerbit, Pengarang, TTerbit);
        listDataB.add(ed);
    }
    
    private void resetInputan(){
        txtKBuku.setText("");
        txtJBuku.setText("");
        txtPenerbit.setText("");
        txtPengarang.setText("");
        txtTTB.setText("");
        txtCariB.setText(null);
        txtKBuku.requestFocus();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKBuku = new javax.swing.JTextField();
        txtJBuku = new javax.swing.JTextField();
        txtPengarang = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        txtTTB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBu = new javax.swing.JTable();
        MKembali = new javax.swing.JButton();
        MKeluar = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        MTambah = new javax.swing.JButton();
        txtCariB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("DAFTAR BUKU PERPUSTAKAAN YANG TERSEDIA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Kode buku");

        jLabel2.setText("Judul buku");

        jLabel3.setText("Penerbit");

        jLabel4.setText("Pengarang");

        jLabel5.setText("Tahun terbit");

        txtKBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKBukuActionPerformed(evt);
            }
        });

        txtJBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJBukuActionPerformed(evt);
            }
        });

        txtPengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPengarangActionPerformed(evt);
            }
        });

        txtPenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPenerbitActionPerformed(evt);
            }
        });

        txtTTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTBActionPerformed(evt);
            }
        });
        txtTTB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTTBKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtJBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtTTB, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        TableBu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableBu);

        MKembali.setText("Kembali");
        MKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKembaliActionPerformed(evt);
            }
        });

        MKeluar.setText("Keluar");
        MKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKeluarActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        MTambah.setText("Tambah");
        MTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTambahActionPerformed(evt);
            }
        });

        txtCariB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariBActionPerformed(evt);
            }
        });
        txtCariB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariBKeyReleased(evt);
            }
        });

        jLabel7.setText("Cari");

        MHapus.setText("Hapus");
        MHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(MTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(12, 12, 12)
                        .addComponent(MHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(196, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariB, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCariB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MTambah)
                            .addComponent(MHapus)
                            .addComponent(MKembali)
                            .addComponent(MKeluar)
                            .addComponent(Edit))
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKBukuActionPerformed

    private void txtJBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJBukuActionPerformed

    private void txtPengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPengarangActionPerformed

    private void txtPenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenerbitActionPerformed

    private void txtTTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTBActionPerformed

    private void MKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKembaliActionPerformed
        new Utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MKembaliActionPerformed

    private void MKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKeluarActionPerformed
        int pilih = javax.swing.JOptionPane.showOptionDialog(this, 
                        "Yakin ingin keluar?", 
                        "", 
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(pilih == javax.swing.JOptionPane.YES_OPTION){
            javax.swing.JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_MKeluarActionPerformed

    private void MTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTambahActionPerformed
        if(txtTTB.getText().equals("")
                 ||txtKBuku.getText().equals("")
                 ||txtJBuku.getText().equals("")
                 ||txtPenerbit.getText().equals("")
                 ||txtPengarang.getText().equals("")){
        javax.swing.JOptionPane.showMessageDialog(this, "Data masih kosong!!");    
        }
        if(txtKBuku.getText().equals("")) txtKBuku.setText("-wajib diisi-");
        if(txtJBuku.getText().equals("")) txtJBuku.setText("-wajib diisi-");
        if(txtPenerbit.getText().equals("")) txtPenerbit.setText("-wajib diisi-");
        if(txtPengarang.getText().equals("")) txtPengarang.setText("-wajib diisi-");
        if(txtTTB.getText().equals("")) txtTTB.setText("0");
        if(txtTTB.getText().equals("0")
                 ||txtKBuku.getText().equals("-wajib diisi-")
                 ||txtJBuku.getText().equals("-wajib diisi-")
                 ||txtPenerbit.getText().equals("-wajib diisi-")
                 ||txtPengarang.getText().equals("-wajib diisi-")){
        javax.swing.JOptionPane.showMessageDialog(this, "Harap isi data yang benar!!");    
        }        
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!!");
        isiData(txtKBuku.getText(),txtJBuku.getText(), txtPenerbit.getText(),txtPengarang.getText(),Integer.parseInt(txtTTB.getText()));
        tampilDataB();
        resetInputan();
        }
    }//GEN-LAST:event_MTambahActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       int i = TableBu.getSelectedRow();
       int a = TableBu.getSelectedRow();
           a = TableBu.convertRowIndexToModel(i);
      if (i == -1||a<=-1) {javax.swing.JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih !!");
        }
         else if(txtKBuku.getText().equals("")
                || txtJBuku.getText().equals("")
                || txtPenerbit.getText().equals("")
                ||txtPengarang.getText().equals("")
                ||txtTTB.getText().equals(""))
        {                        
        txtKBuku.setText(TableBu.getValueAt(i, 0).toString());
        txtJBuku.setText(TableBu.getValueAt(i, 1).toString());
        txtPenerbit.setText(TableBu.getValueAt(i, 2).toString());
        txtPengarang.setText(TableBu.getValueAt(i, 3).toString());
        txtTTB.setText(TableBu.getValueAt(i, 4).toString());      
        }
         else if(txtTTB.getText().equals("")
                 ||txtKBuku.getText().equals("")
                 ||txtJBuku.getText().equals("")
                 ||txtPenerbit.getText().equals("")
                 ||txtPengarang.getText().equals(""))
         {
             txtTTB.setText("0");
             txtKBuku.setText("-wajib diisi-");
             txtPenerbit.setText("-wajib diisi-");
             txtPengarang.setText("-wajib diisi-");
         }
         else if(txtTTB.getText().equals("0")
                 ||txtKBuku.getText().equals("-wajib diisi-")
                 ||txtJBuku.getText().equals("-wajib diisi-")
                 ||txtPenerbit.getText().equals("-wajib diisi-")
                 ||txtPengarang.getText().equals("-wajib diisi-")){
        javax.swing.JOptionPane.showMessageDialog(this, "Harap isi data yang benar!!");    
        }
         else if(i>=0){        
             isiData(txtKBuku.getText(),txtJBuku.getText(), txtPenerbit.getText(),txtPengarang.getText(),Integer.parseInt(txtTTB.getText()));
             listDataB.remove(a);
             TableBu.setRowSorter(null);
             tampilDataB();
             javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil di edit");
             resetInputan();           
         }
         else {
        isiData(txtKBuku.getText(),txtJBuku.getText(), txtPenerbit.getText(),txtPengarang.getText(),Integer.parseInt(txtTTB.getText()));
        listDataB.remove(i);
        TableBu.setRowSorter(null);
        tampilDataB();
        javax.swing.JOptionPane.showMessageDialog(this, "Data sudah di edit");
        resetInputan();   
        }
      
}//GEN-LAST:event_EditActionPerformed

    private void txtCariBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBKeyReleased
        String cari = txtCariB.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel2);
        TableBu.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari));
        if (TableBu.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "Item yang di cari tidak ada di list");
            TableBu.setRowSorter(null);
            txtCariB.setText("");
            resetInputan();
        }                 
    }//GEN-LAST:event_txtCariBKeyReleased

    private void MHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MHapusActionPerformed

        int a = TableBu.getSelectedRow();
              a = TableBu.convertRowIndexToModel(a);
        if (a <= -1) {javax.swing.JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih !!");
        }else if(a>=0) {
            listDataB.remove(a);
            javax.swing.JOptionPane.showMessageDialog(null, "Data berhasil dihapus !!");
        }
        else {           
            javax.swing.JOptionPane.showMessageDialog(null, "Hapus data error, coba lagi");

        }
        resetInputan();
        TableBu.setRowSorter(null);
        tampilDataB();
}//GEN-LAST:event_MHapusActionPerformed

    private void txtTTBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTTBKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||(ch==KeyEvent.VK_BACK_SPACE)||(ch==KeyEvent.VK_DELETE)))
        {evt.consume();
        
        }
    }//GEN-LAST:event_txtTTBKeyTyped

    private void txtCariBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBKeyPressed
    }//GEN-LAST:event_txtCariBKeyPressed

    private void txtCariBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariBActionPerformed

    }//GEN-LAST:event_txtCariBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new DaftarBuku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton MHapus;
    private javax.swing.JButton MKeluar;
    private javax.swing.JButton MKembali;
    private javax.swing.JButton MTambah;
    private javax.swing.JTable TableBu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCariB;
    private javax.swing.JTextField txtJBuku;
    private javax.swing.JTextField txtKBuku;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtTTB;
    // End of variables declaration//GEN-END:variables
}
