/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Kembalikan.java
 *
 * Created on May 29, 2021, 12:22:37 PM
 */
package ProjekUAS;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Yuu
 */
public class Kembalikan extends javax.swing.JFrame {
public static int daysBetween(Date tanggalpin, Date tanggalpen){
     return (int)( (tanggalpen.getTime() - tanggalpin.getTime()) / (1000 * 60 * 60 * 24));
     }
public static ArrayList<DataBuku> listkembali = new ArrayList<DataBuku>();
public static ArrayList<KembaliData> listpinjamB = new ArrayList<KembaliData>();
public static ArrayList<KembaliData> getList() {
       return listpinjamB;
}
ArrayList<DataBuku> listdataB = DaftarBuku.getList();
DefaultTableModel tabelModel;
    public Kembalikan() {
        setSize(900, 600);
        setLocationRelativeTo(null);
        initComponents();
        tampilDataP();
    }
 
    private void tampilDataP(){
        String[] kolom = {"KODE PINJAM","KODE ANGGOTA","NAMA","KODE BUKU","JUDUL BUKU","PENERBIT","PENGARANG","TAHUN TERBIT","TANGGAL PINJAM"};
        Object[][] objData = new Object[listpinjamB.size()][9];//jumlah kolom
        
        int i = 0;
        for(KembaliData n : listpinjamB){
            String[] arrData = {String.valueOf(n.getKpinjam()),n.getKang(),n.getNang(),n.getKbuku(),n.getJbuku(),n.getPenerbit(),n.getPengarang(), String.valueOf(n.getTTerbit()),n.getTanggalpin()};
            objData[i] = arrData;
            i++;
        }
        
        tabelModel = new DefaultTableModel(objData,kolom){
            //membuat tabel tidak bisa diedit saat diklik
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        
        TablePinjam.setModel(tabelModel);
        
        
    }
    private void resetInputan(){
        txtKpin.setText("");
        txtNama.setText("");
        txtKBuku.setText("");
        txtID.setText("");
        txtLBuku.setText("-");
        txtJBuku.setText("-");
        txtPenerbit.setText("-");
        txtPengarang.setText("-");
        txtTTerbit.setText("-");
        txtTpin.setText("");
        txtTpen.setText("");
        txtLambat.setText("");
        txtDenda.setText("");
        txtKpin.requestFocus();

    }
    public void isiData(String KBuku, String JBuku, String Penerbit,String Pengarang, int TTerbit){
        DataBuku ed = new DataBuku(KBuku, JBuku, Penerbit, Pengarang, TTerbit);
        listkembali.add(ed);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKpin = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKBuku = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTpin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtLambat = new javax.swing.JTextField();
        txtDenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTpen = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablePinjam = new javax.swing.JTable();
        MHapus = new javax.swing.JButton();
        MKembali = new javax.swing.JButton();
        MKeluar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtLBuku = new javax.swing.JLabel();
        txtJBuku = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JLabel();
        txtPengarang = new javax.swing.JLabel();
        txtTTerbit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Simpan = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel9.setText("PENGEMBALIAN BUKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(33, 33, 33))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Kode Peminjaman");

        jLabel2.setText("ID Anggota");

        jLabel3.setText("Nama Anggota");

        jLabel4.setText("Kode Buku");

        txtKpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKpinActionPerformed(evt);
            }
        });
        txtKpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKpinKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKpinKeyTyped(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNamaKeyReleased(evt);
            }
        });

        txtKBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKBukuActionPerformed(evt);
            }
        });
        txtKBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKBukuKeyReleased(evt);
            }
        });

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKpin, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Tanggal Pinjam");

        txtTpin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTpinKeyTyped(evt);
            }
        });

        jLabel6.setText("Keterlambatan");

        jLabel7.setText("Denda");

        txtLambat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLambatKeyTyped(evt);
            }
        });

        txtDenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDendaKeyTyped(evt);
            }
        });

        jLabel8.setText("KETERANGAN : DENDA 2000/HARI");

        jLabel10.setText("Tanggal Pengembalian");

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(txtTpin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(txtLambat, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtTpen, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTpen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtLambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Hitung))
                .addContainerGap())
        );

        TablePinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePinjamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePinjam);

        MHapus.setText("Reset");
        MHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MHapusActionPerformed(evt);
            }
        });

        MKembali.setText("Kembali");
        MKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKembaliActionPerformed(evt);
            }
        });

        MKeluar.setText("Keluar");
        MKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MKeluarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel18.setText("Buku yang dipinjam :");

        jLabel19.setText("Kode buku       :");

        jLabel20.setText("Judul buku       :");

        jLabel21.setText("Penerbit          :");

        jLabel22.setText("Pengarang      :");

        jLabel23.setText("Tahun terbit    :");

        txtLBuku.setText("-");
        txtLBuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLBukuKeyTyped(evt);
            }
        });

        txtJBuku.setText("-");

        txtPenerbit.setText("-");

        txtPengarang.setText("-");

        txtTTerbit.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTTerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtJBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(txtLBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtLBuku))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtJBuku))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtPenerbit))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtPengarang))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtTTerbit))
                .addGap(25, 25, 25))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel11.setText("Catatan :");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel12.setText("Jika ada keterlambatan");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel13.setText("Harap membayar denda ditempat ya...");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel14.setText("Akan ada denda jika mengembalikan");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 24));
        jLabel15.setText("buku jika lebih dari 3 hari dipinjam...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MHapus)
                    .addComponent(Simpan)
                    .addComponent(MKembali)
                    .addComponent(MKeluar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
      int hari= 0;
      int denda = 2000;
      int hitungdenda;
      try{
                   String tanggalpin=txtTpin.getText();
                   String tanggalpen=txtTpen.getText();

      Date hari1 = new SimpleDateFormat("dd-MM-yyyy").parse(tanggalpin);
      Date hari2 = new SimpleDateFormat("dd-MM-yyyy").parse(tanggalpen);

      Calendar cal1=Calendar.getInstance();
      cal1.setTime(hari1);

      Calendar cal2=Calendar.getInstance();
      cal2.setTime(hari2);

      hari=daysBetween(cal1.getTime(),cal2.getTime());
      }
      catch(Exception ex){}
      
      if (hari>=4){
       hari=hari-3;
       hitungdenda=hari*denda;
       txtDenda.setText(""+hitungdenda);
       txtLambat.setText(""+hari+" hari");
      }
      else if(txtTpen.getText().equals("")){
          javax.swing.JOptionPane.showMessageDialog(this, "Masukan tanggal yang benar !!");
          txtLambat.setText("");
          txtDenda.setText("");
          txtTpen.requestFocus();
          
      }        
      else if(hari==3||hari==2||hari==1||hari==0){
         txtDenda.setText("tidak ada denda");
         txtLambat.setText("0 hari");
      }
      else if(hari<=-1){
         javax.swing.JOptionPane.showMessageDialog(this, "Masukan tanggal yang benar !!");
          txtTpen.setText("");
          txtLambat.setText("");
          txtDenda.setText("");
          txtTpen.requestFocus();
      }
      else{
          javax.swing.JOptionPane.showMessageDialog(this, "Masukan tanggal yang benar !!");
          txtTpen.setText("");
          txtLambat.setText("");
          txtDenda.setText("");
          txtTpen.requestFocus();
      }
    }//GEN-LAST:event_HitungActionPerformed

    private void MKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKembaliActionPerformed
        new Utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MKembaliActionPerformed

    private void MKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MKeluarActionPerformed
        int pilih = javax.swing.JOptionPane.showOptionDialog(this, 
                        "Yakin ingin keluar?", 
                        "", 
                        javax.swing.JOptionPane.YES_NO_OPTION, 
                        javax.swing.JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(pilih == javax.swing.JOptionPane.YES_OPTION){
            javax.swing.JOptionPane.showMessageDialog(this, "Program Akan Keluar");
            System.exit(0);
        }
    }//GEN-LAST:event_MKeluarActionPerformed

    private void TablePinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePinjamMouseClicked
           int i = TablePinjam.getSelectedRow();   
             if(i>=0)
        {
        txtKpin.setText(TablePinjam.getValueAt(i, 0).toString());
        txtID.setText(TablePinjam.getValueAt(i, 1).toString());
        txtNama.setText(TablePinjam.getValueAt(i, 2).toString());
        txtKBuku.setText(TablePinjam.getValueAt(i, 3).toString());    
        txtLBuku.setText(TablePinjam.getValueAt(i, 3).toString());
        txtJBuku.setText(TablePinjam.getValueAt(i, 4).toString());
        txtPenerbit.setText(TablePinjam.getValueAt(i, 5).toString());
        txtPengarang.setText(TablePinjam.getValueAt(i, 6).toString());
        txtTTerbit.setText(TablePinjam.getValueAt(i, 7).toString());
        txtTpin.setText(TablePinjam.getValueAt(i, 8).toString());
        txtTpen.setText("");
        txtLambat.setText("");
        txtDenda.setText("");
        }
    }//GEN-LAST:event_TablePinjamMouseClicked

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        int i = TablePinjam.getSelectedRow();
        int a = TablePinjam.getSelectedRow();
           a = TablePinjam.convertRowIndexToModel(0);
           a = TablePinjam.convertRowIndexToModel(i);
        if(i == -1||a<=-1||txtKpin.getText().equals("")||txtKBuku.getText().equals("")||txtID.getText().equals("")||txtNama.getText().equals("")){
        javax.swing.JOptionPane.showMessageDialog(this, "Tidak ada data yang dipilih! / Data kosong!");    
        }
        else if (txtTpen.getText().equals("")||txtDenda.getText().equals("")||txtLambat.getText().equals("")){
        javax.swing.JOptionPane.showMessageDialog(this, "Silahkan input tgl dan Hitung keterlambatan dulu!!");
        }
        else if(i==0||i==1||i==2){
        isiData(txtID.getText(),txtJBuku.getText(), txtPenerbit.getText(),txtPengarang.getText(),Integer.parseInt(txtTTerbit.getText()));
        listdataB.addAll(listkembali);    
        listpinjamB.remove(a);
        javax.swing.JOptionPane.showMessageDialog(this, "Buku sudah dikembalikan!!");
        TablePinjam.setRowSorter(null);
        tampilDataP();
        resetInputan();
        }
        
        else {isiData(txtID.getText(),txtJBuku.getText(), txtPenerbit.getText(),txtPengarang.getText(),Integer.parseInt(txtTTerbit.getText()));
        listdataB.addAll(listkembali);
        listpinjamB.remove(i);
        javax.swing.JOptionPane.showMessageDialog(this, "Buku sudah dikembalikan!!");
        TablePinjam.setRowSorter(null); 
        tampilDataP();
        resetInputan();       
        }

    }//GEN-LAST:event_SimpanActionPerformed

    private void txtLBukuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLBukuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLBukuKeyTyped

    private void txtTpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTpinKeyTyped
        char ch=evt.getKeyChar();
        evt.consume();
    }//GEN-LAST:event_txtTpinKeyTyped

    private void txtDendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDendaKeyTyped
        char ch=evt.getKeyChar();
        evt.consume();
    }//GEN-LAST:event_txtDendaKeyTyped

    private void txtLambatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLambatKeyTyped
        char ch=evt.getKeyChar();
        evt.consume();
    }//GEN-LAST:event_txtLambatKeyTyped

    private void txtKpinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKpinKeyReleased

    }//GEN-LAST:event_txtKpinKeyReleased

    private void txtIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyReleased

    }//GEN-LAST:event_txtIDKeyReleased

    private void txtNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyReleased

    }//GEN-LAST:event_txtNamaKeyReleased

    private void txtKBukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKBukuKeyReleased

    }//GEN-LAST:event_txtKBukuKeyReleased

    private void txtKBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKBukuActionPerformed
      String cari = txtKBuku.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel);
        TablePinjam.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari,3));//fungsi (?i)Agar huruf kapital dan kecil tetap dibaca
        if (TablePinjam.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "Kode buku tidak ada di list");
            TablePinjam.setRowSorter(null);
            txtKBuku.setText("");
    }                    
    }//GEN-LAST:event_txtKBukuActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        String cari = txtNama.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel);
        TablePinjam.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari,2));//fungsi (?i)Agar huruf kapital dan kecil tetap dibaca
        if (TablePinjam.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "Nama anggota tidak ada di list");
            TablePinjam.setRowSorter(null);
            txtNama.setText("");
    }                    
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
      String cari = txtID.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel);
        TablePinjam.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari,1));//fungsi (?i)Agar huruf kapital dan kecil tetap dibaca
        if (TablePinjam.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "ID anggota tidak ada di list");
            TablePinjam.setRowSorter(null);
            txtID.setText("");
    }                 
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtKpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKpinActionPerformed
      String cari = txtKpin.getText();
        TableRowSorter tr = new TableRowSorter(tabelModel);
        TablePinjam.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)^"+cari,0));//fungsi (?i)Agar huruf kapital dan kecil tetap dibaca
        if (TablePinjam.getRowCount()==0){
            javax.swing.JOptionPane.showMessageDialog(null, "Kode pinjam tidak ada di list");
            TablePinjam.setRowSorter(null);
            txtKpin.setText("");
    }                                              
    }//GEN-LAST:event_txtKpinActionPerformed

    private void txtKpinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKpinKeyTyped
   char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)||(ch==KeyEvent.VK_BACK_SPACE)||(ch==KeyEvent.VK_DELETE)))
        {evt.consume();
    }//GEN-LAST:event_txtKpinKeyTyped
    }
   private void MHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MHapusActionPerformed
        TablePinjam.setRowSorter(null);
        tampilDataP();
        resetInputan();
   }//GEN-LAST:event_MHapusActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kembalikan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hitung;
    private javax.swing.JButton MHapus;
    private javax.swing.JButton MKeluar;
    private javax.swing.JButton MKembali;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable TablePinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtJBuku;
    private javax.swing.JTextField txtKBuku;
    private javax.swing.JTextField txtKpin;
    private javax.swing.JLabel txtLBuku;
    private javax.swing.JTextField txtLambat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JLabel txtPenerbit;
    private javax.swing.JLabel txtPengarang;
    private javax.swing.JLabel txtTTerbit;
    private javax.swing.JTextField txtTpen;
    private javax.swing.JTextField txtTpin;
    // End of variables declaration//GEN-END:variables
}
